// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AckMessageReducer from "./ack_message_reducer";
import ClaimFilesReducer from "./claim_files_reducer";
import HeartbeatReducer from "./heartbeat_reducer";
import IngestActivityReducer from "./ingest_activity_reducer";
import JoinMemberReducer from "./join_member_reducer";
import MarkDeliveredReducer from "./mark_delivered_reducer";
import OfferHandoffReducer from "./offer_handoff_reducer";
import PostMessageReducer from "./post_message_reducer";
import RecordDiffReducer from "./record_diff_reducer";
import RecordTestRunReducer from "./record_test_run_reducer";
import ReleaseFilesReducer from "./release_files_reducer";
import RemoveMemberReducer from "./remove_member_reducer";
import ReportStatusReducer from "./report_status_reducer";
import RespondHandoffReducer from "./respond_handoff_reducer";
import SeedRepoReducer from "./seed_repo_reducer";
import SetConfigReducer from "./set_config_reducer";
import SetPausedReducer from "./set_paused_reducer";
import SetTaskItemsReducer from "./set_task_items_reducer";
import StartTaskReducer from "./start_task_reducer";
import SubmitEvidenceReducer from "./submit_evidence_reducer";
import SubmitReviewReducer from "./submit_review_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ActivityRow from "./activity_table";
import AgentRow from "./agent_table";
import CertificationRow from "./certification_table";
import ClaimRow from "./claim_table";
import ConfigRow from "./config_table";
import DiffRow from "./diff_table";
import HandoffRow from "./handoff_table";
import MemberRow from "./member_table";
import MessageRow from "./message_table";
import PlantRow from "./plant_table";
import ReviewRow from "./review_table";
import TaskRow from "./task_table";
import TaskItemRow from "./task_item_table";
import TestRunRow from "./test_run_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  activity: __table({
    name: 'activity',
    indexes: [
      { accessor: 'id', name: 'activity_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'activity_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActivityRow),
  agent: __table({
    name: 'agent',
    indexes: [
      { accessor: 'sessionId', name: 'agent_session_id_idx_btree', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'agent_session_id_key', constraint: 'unique', columns: ['sessionId'] },
    ],
  }, AgentRow),
  certification: __table({
    name: 'certification',
    indexes: [
      { accessor: 'id', name: 'certification_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'certification_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CertificationRow),
  claim: __table({
    name: 'claim',
    indexes: [
      { accessor: 'id', name: 'claim_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'claim_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClaimRow),
  config: __table({
    name: 'config',
    indexes: [
      { accessor: 'key', name: 'config_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'config_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, ConfigRow),
  diff: __table({
    name: 'diff',
    indexes: [
      { accessor: 'id', name: 'diff_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'diff_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DiffRow),
  handoff: __table({
    name: 'handoff',
    indexes: [
      { accessor: 'id', name: 'handoff_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'handoff_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HandoffRow),
  member: __table({
    name: 'member',
    indexes: [
      { accessor: 'handle', name: 'member_handle_idx_btree', algorithm: 'btree', columns: [
        'handle',
      ] },
    ],
    constraints: [
      { name: 'member_handle_key', constraint: 'unique', columns: ['handle'] },
    ],
  }, MemberRow),
  message: __table({
    name: 'message',
    indexes: [
      { accessor: 'id', name: 'message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MessageRow),
  plant: __table({
    name: 'plant',
    indexes: [
      { accessor: 'path', name: 'plant_path_idx_btree', algorithm: 'btree', columns: [
        'path',
      ] },
    ],
    constraints: [
      { name: 'plant_path_key', constraint: 'unique', columns: ['path'] },
    ],
  }, PlantRow),
  review: __table({
    name: 'review',
    indexes: [
      { accessor: 'id', name: 'review_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'review_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ReviewRow),
  task: __table({
    name: 'task',
    indexes: [
      { accessor: 'id', name: 'task_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'task_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TaskRow),
  taskItem: __table({
    name: 'task_item',
    indexes: [
      { accessor: 'id', name: 'task_item_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'task_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TaskItemRow),
  testRun: __table({
    name: 'test_run',
    indexes: [
      { accessor: 'id', name: 'test_run_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'test_run_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TestRunRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("ack_message", AckMessageReducer),
  __reducerSchema("claim_files", ClaimFilesReducer),
  __reducerSchema("heartbeat", HeartbeatReducer),
  __reducerSchema("ingest_activity", IngestActivityReducer),
  __reducerSchema("join_member", JoinMemberReducer),
  __reducerSchema("mark_delivered", MarkDeliveredReducer),
  __reducerSchema("offer_handoff", OfferHandoffReducer),
  __reducerSchema("post_message", PostMessageReducer),
  __reducerSchema("record_diff", RecordDiffReducer),
  __reducerSchema("record_test_run", RecordTestRunReducer),
  __reducerSchema("release_files", ReleaseFilesReducer),
  __reducerSchema("remove_member", RemoveMemberReducer),
  __reducerSchema("report_status", ReportStatusReducer),
  __reducerSchema("respond_handoff", RespondHandoffReducer),
  __reducerSchema("seed_repo", SeedRepoReducer),
  __reducerSchema("set_config", SetConfigReducer),
  __reducerSchema("set_paused", SetPausedReducer),
  __reducerSchema("set_task_items", SetTaskItemsReducer),
  __reducerSchema("start_task", StartTaskReducer),
  __reducerSchema("submit_evidence", SubmitEvidenceReducer),
  __reducerSchema("submit_review", SubmitReviewReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

