// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Activity = __t.object("Activity", {
  id: __t.u64(),
  at: __t.timestamp(),
  handle: __t.string(),
  sessionId: __t.option(__t.string()),
  kind: __t.string(),
  path: __t.option(__t.string()),
  detail: __t.string(),
});
export type Activity = __Infer<typeof Activity>;

export const Agent = __t.object("Agent", {
  sessionId: __t.string(),
  handle: __t.string(),
  kind: __t.string(),
  parentSessionId: __t.option(__t.string()),
  status: __t.string(),
  currentPath: __t.option(__t.string()),
  currentAction: __t.string(),
  lastSeen: __t.timestamp(),
});
export type Agent = __Infer<typeof Agent>;

export const Certification = __t.object("Certification", {
  id: __t.u64(),
  path: __t.string(),
  handle: __t.string(),
  task: __t.string(),
  result: __t.string(),
  reason: __t.string(),
  at: __t.timestamp(),
});
export type Certification = __Infer<typeof Certification>;

export const Claim = __t.object("Claim", {
  id: __t.u64(),
  path: __t.string(),
  handle: __t.string(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type Claim = __Infer<typeof Claim>;

export const Config = __t.object("Config", {
  key: __t.string(),
  value: __t.string(),
});
export type Config = __Infer<typeof Config>;

export const Diff = __t.object("Diff", {
  id: __t.u64(),
  handle: __t.string(),
  path: __t.string(),
  at: __t.timestamp(),
  commit: __t.option(__t.string()),
});
export type Diff = __Infer<typeof Diff>;

export const ExpireClaimsTimer = __t.object("ExpireClaimsTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ExpireClaimsTimer = __Infer<typeof ExpireClaimsTimer>;

export const Handoff = __t.object("Handoff", {
  id: __t.u64(),
  fromHandle: __t.string(),
  toHandle: __t.string(),
  task: __t.string(),
  notes: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Handoff = __Infer<typeof Handoff>;

export const Member = __t.object("Member", {
  handle: __t.string(),
  color: __t.string(),
  online: __t.bool(),
  paused: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type Member = __Infer<typeof Member>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  fromHandle: __t.string(),
  fromSession: __t.option(__t.string()),
  toHandle: __t.string(),
  kind: __t.string(),
  body: __t.string(),
  status: __t.string(),
  sentAt: __t.timestamp(),
  deliveredAt: __t.option(__t.timestamp()),
  ackedAt: __t.option(__t.timestamp()),
});
export type Message = __Infer<typeof Message>;

export const Plant = __t.object("Plant", {
  path: __t.string(),
  bed: __t.string(),
  lines: __t.u32(),
  stage: __t.string(),
  bugs: __t.u32(),
  lastActivity: __t.timestamp(),
  lastTouchedBy: __t.option(__t.string()),
  lastDiffAt: __t.option(__t.timestamp()),
  lastBloomAt: __t.option(__t.timestamp()),
});
export type Plant = __Infer<typeof Plant>;

export const Review = __t.object("Review", {
  id: __t.u64(),
  path: __t.string(),
  handle: __t.string(),
  ok: __t.bool(),
  at: __t.timestamp(),
});
export type Review = __Infer<typeof Review>;

export const SeedFile = __t.object("SeedFile", {
  path: __t.string(),
  lines: __t.u32(),
});
export type SeedFile = __Infer<typeof SeedFile>;

export const SweepTimer = __t.object("SweepTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type SweepTimer = __Infer<typeof SweepTimer>;

export const Task = __t.object("Task", {
  id: __t.u64(),
  handle: __t.string(),
  title: __t.string(),
  status: __t.string(),
  bed: __t.string(),
  paths: __t.array(__t.string()),
  blockedReason: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  doneAt: __t.option(__t.timestamp()),
});
export type Task = __Infer<typeof Task>;

export const TaskItem = __t.object("TaskItem", {
  id: __t.u64(),
  taskId: __t.u64(),
  ord: __t.u32(),
  text: __t.string(),
  state: __t.string(),
});
export type TaskItem = __Infer<typeof TaskItem>;

export const TaskItemIn = __t.object("TaskItemIn", {
  text: __t.string(),
  state: __t.string(),
});
export type TaskItemIn = __Infer<typeof TaskItemIn>;

export const TestRun = __t.object("TestRun", {
  id: __t.u64(),
  handle: __t.string(),
  repo: __t.string(),
  command: __t.string(),
  exitCode: __t.i32(),
  at: __t.timestamp(),
});
export type TestRun = __Infer<typeof TestRun>;

