// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  handle: __t.string(),
  sessionId: __t.option(__t.string()),
  kind: __t.string(),
  path: __t.option(__t.string()),
  lines: __t.option(__t.u32()),
  detail: __t.option(__t.string()),
  parentSessionId: __t.option(__t.string()),
};
