// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  handle: __t.string(),
  kind: __t.string(),
  parentSessionId: __t.option(__t.string()).name("parent_session_id"),
  status: __t.string(),
  currentPath: __t.option(__t.string()).name("current_path"),
  currentAction: __t.string().name("current_action"),
  lastSeen: __t.timestamp().name("last_seen"),
});
