// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  fromHandle: __t.string().name("from_handle"),
  fromSession: __t.option(__t.string()).name("from_session"),
  toHandle: __t.string().name("to_handle"),
  kind: __t.string(),
  body: __t.string(),
  status: __t.string(),
  sentAt: __t.timestamp().name("sent_at"),
  deliveredAt: __t.option(__t.timestamp()).name("delivered_at"),
  ackedAt: __t.option(__t.timestamp()).name("acked_at"),
});
