// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AckMessageReducer from "../ack_message_reducer";
import ClaimFilesReducer from "../claim_files_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import IngestActivityReducer from "../ingest_activity_reducer";
import JoinMemberReducer from "../join_member_reducer";
import MarkDeliveredReducer from "../mark_delivered_reducer";
import OfferHandoffReducer from "../offer_handoff_reducer";
import PostMessageReducer from "../post_message_reducer";
import RecordDiffReducer from "../record_diff_reducer";
import RecordTestRunReducer from "../record_test_run_reducer";
import ReleaseFilesReducer from "../release_files_reducer";
import RemoveMemberReducer from "../remove_member_reducer";
import ReportStatusReducer from "../report_status_reducer";
import RespondHandoffReducer from "../respond_handoff_reducer";
import SeedRepoReducer from "../seed_repo_reducer";
import SetConfigReducer from "../set_config_reducer";
import SetPausedReducer from "../set_paused_reducer";
import SetTaskItemsReducer from "../set_task_items_reducer";
import StartTaskReducer from "../start_task_reducer";
import SubmitEvidenceReducer from "../submit_evidence_reducer";
import SubmitReviewReducer from "../submit_review_reducer";

export type AckMessageParams = __Infer<typeof AckMessageReducer>;
export type ClaimFilesParams = __Infer<typeof ClaimFilesReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type IngestActivityParams = __Infer<typeof IngestActivityReducer>;
export type JoinMemberParams = __Infer<typeof JoinMemberReducer>;
export type MarkDeliveredParams = __Infer<typeof MarkDeliveredReducer>;
export type OfferHandoffParams = __Infer<typeof OfferHandoffReducer>;
export type PostMessageParams = __Infer<typeof PostMessageReducer>;
export type RecordDiffParams = __Infer<typeof RecordDiffReducer>;
export type RecordTestRunParams = __Infer<typeof RecordTestRunReducer>;
export type ReleaseFilesParams = __Infer<typeof ReleaseFilesReducer>;
export type RemoveMemberParams = __Infer<typeof RemoveMemberReducer>;
export type ReportStatusParams = __Infer<typeof ReportStatusReducer>;
export type RespondHandoffParams = __Infer<typeof RespondHandoffReducer>;
export type SeedRepoParams = __Infer<typeof SeedRepoReducer>;
export type SetConfigParams = __Infer<typeof SetConfigReducer>;
export type SetPausedParams = __Infer<typeof SetPausedReducer>;
export type SetTaskItemsParams = __Infer<typeof SetTaskItemsReducer>;
export type StartTaskParams = __Infer<typeof StartTaskReducer>;
export type SubmitEvidenceParams = __Infer<typeof SubmitEvidenceReducer>;
export type SubmitReviewParams = __Infer<typeof SubmitReviewReducer>;

