// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  path: __t.string().primaryKey(),
  bed: __t.string(),
  lines: __t.u32(),
  stage: __t.string(),
  bugs: __t.u32(),
  lastActivity: __t.timestamp().name("last_activity"),
  lastTouchedBy: __t.option(__t.string()).name("last_touched_by"),
  lastDiffAt: __t.option(__t.timestamp()).name("last_diff_at"),
  lastBloomAt: __t.option(__t.timestamp()).name("last_bloom_at"),
});
